services:
  inventory-db:
    image: mysql:${DB_TAG:-latest}
    container_name: inventory_db_container
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USER}", "-p${DB_PASSWORD}" ]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: inventory_db
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    networks:
      - ecommerce-network
#  inventory-db:
#    image: oscarfonts/h2:latest  # A popular lightweight H2 server image
#    environment:
#     - H2_OPTIONS=-ifNotExists
#    ports:
#      - "1521:1521"  # H2 TCP Port
#      - "8082:8082"  # H2 Web Console Port
#    networks:
#      - ecommerce-network

  inventory-service:
    image: ${DOCKER_USERNAME}/inventory-service:${IMAGE_TAG:-latest}
    container_name: inventory-service_${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: inventory-service/Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=${INVENTORY_DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_DATASOURCE_DRIVER=${MYSQL_DRIVER}
      - SPRING_JPA_DIALECT=${MYSQL_DIALECT}
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5000
    ports:
      - "8081:8080"
      - "5001:5000"
    depends_on:
      inventory-db:
        condition: service_healthy
    networks:
      - ecommerce-network

  order-db:
    image: mysql:${DB_TAG:-latest}
    container_name: order_db_container
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USER}", "-p${DB_PASSWORD}" ]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: order_db
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ecommerce-network

#  order-db:
#    image: oscarfonts/h2:latest  # A popular lightweight H2 server image
#    environment:
#      - H2_OPTIONS=-ifNotExists
#    ports:
#      - "3307:3306"
#    networks:
#      - ecommerce-network


  order-service:
    image: ${DOCKER_USERNAME}/order-service:${IMAGE_TAG:-latest}
    container_name: order-service_${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: order-service/Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=${ORDER_DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_DATASOURCE_DRIVER=${MYSQL_DRIVER}
      - SPRING_JPA_DIALECT=${MYSQL_DIALECT}
      - INVENTORY_SERVICE_URL=http://inventory-service:8080
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5000
    ports:
      - "8082:8080"   # application port 8080 in container
      - "5002:5000"
    depends_on:
      order-db:
        condition: service_healthy
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  mysql-data:
