services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # High-level: This tells Kafka how to be reached from both inside and outside Docker
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER://kafka:29092,LISTENER_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER:PLAINTEXT, LISTENER_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    # Web UI for Kafka - accessible at http://localhost:9000
    # Web UI for Kafka - accessible at http://localhost:9000
  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
    depends_on:
      - kafka
  # inventory-db config
  inventory-db:
    image: mysql:${DB_TAG:-latest}
    container_name: inventory_db_container
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USER}", "-p${DB_PASSWORD}" ]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: inventory_db
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - inventory-data:/var/lib/mysql
    networks:
      - ecommerce-network

  inventory-service:
    image: ${DOCKER_USERNAME}/inventory-service:${IMAGE_TAG:-latest}
    container_name: inventory-service_${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: inventory-service/Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=${INVENTORY_DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_DATASOURCE_DRIVER=${MYSQL_DRIVER}
      - SPRING_JPA_DIALECT=${MYSQL_DIALECT}
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5000
    ports:
      - "8081:8080"
      - "5001:5000"
    depends_on:
      inventory-db:
        condition: service_healthy
    networks:
      - ecommerce-network

  order-db:
    image: mysql:${DB_TAG:-latest}
    container_name: order_db_container
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USER}", "-p${DB_PASSWORD}" ]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: order_db
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - order-data:/var/lib/mysql
    networks:
      - ecommerce-network

  order-service:
    image: ${DOCKER_USERNAME}/order-service:${IMAGE_TAG:-latest}
    container_name: order-service_${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: order-service/Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=${ORDER_DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_DATASOURCE_DRIVER=${MYSQL_DRIVER}
      - SPRING_JPA_DIALECT=${MYSQL_DIALECT}
      - INVENTORY_SERVICE_URL=http://inventory-service:8080
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5000
    ports:
      - "8082:8080"   # application port 8080 in container
      - "5002:5000"
    depends_on:
      order-db:
        condition: service_healthy
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  order-data:
  inventory-data:
