server:
  port: 8080

spring:
  application:
    name: inventory-service
  sql:
    init:
      #mode: always
      mode : never  # This stops data.sql from running on startup
      data-locations: classpath:data.sql
      # schema-locations: classpath:schema.sql # Uncomment if needed

  datasource:
    # 1. For Mysql - Docker uses 'inventory-db', Local IDE uses 'localhost'
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:testdb}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.h2.Driver}

  # Enable H2 Console for local testing if needed
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        # MANDATORY: Allows access from your browser to the Docker container
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: ${SPRING_JPA_DIALECT:org.hibernate.dialect.H2Dialect}
    # Crucial: Ensures Hibernate creates tables BEFORE data.sql runs
    defer-datasource-initialization: true

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

inventory:
  low-stock-threshold: 10

