server:
  port: 8080

spring:
  application:
    name: inventory-service

  datasource:
    # 1. For Mysql - Docker uses 'inventory-db', Local IDE uses 'localhost'
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:testdb}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.h2.Driver}

  # Enable H2 Console for local testing if needed
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        # MANDATORY: Allows access from your browser to the Docker container
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#   database-platform: ${SPRING_JPA_DIALECT:org.hibernate.dialect.MySQL8Dialect}
    database-platform: ${SPRING_JPA_DIALECT:org.hibernate.dialect.H2Dialect}
